// Vanilla Minecraft Java Edition entity type constants.
// Copy the names you need into your own project until RedScript gets imports.

// Hostile mobs
const ZOMBIE: string = "minecraft:zombie"
const SKELETON: string = "minecraft:skeleton"
const CREEPER: string = "minecraft:creeper"
const SPIDER: string = "minecraft:spider"
const CAVE_SPIDER: string = "minecraft:cave_spider"
const ENDERMAN: string = "minecraft:enderman"
const WITCH: string = "minecraft:witch"
const PHANTOM: string = "minecraft:phantom"
const DROWNED: string = "minecraft:drowned"
const HUSK: string = "minecraft:husk"
const STRAY: string = "minecraft:stray"
const WARDEN: string = "minecraft:warden"
const PILLAGER: string = "minecraft:pillager"
const RAVAGER: string = "minecraft:ravager"
const VINDICATOR: string = "minecraft:vindicator"
const EVOKER: string = "minecraft:evoker"
const VEXE: string = "minecraft:vex"
const ZOMBIE_VILLAGER: string = "minecraft:zombie_villager"
const BLAZE: string = "minecraft:blaze"
const GHAST: string = "minecraft:ghast"
const MAGMA_CUBE: string = "minecraft:magma_cube"
const SLIME: string = "minecraft:slime"
const PIGLIN_BRUTE: string = "minecraft:piglin_brute"
const HOGLIN: string = "minecraft:hoglin"
const ZOGLIN: string = "minecraft:zoglin"
const ENDERMITE: string = "minecraft:endermite"
const SILVERFISH: string = "minecraft:silverfish"
const SHULKER: string = "minecraft:shulker"
const GUARDIAN: string = "minecraft:guardian"
const ELDER_GUARDIAN: string = "minecraft:elder_guardian"
const BOGGED: string = "minecraft:bogged"
const BREEZE: string = "minecraft:breeze"

// Passive mobs
const PIG: string = "minecraft:pig"
const COW: string = "minecraft:cow"
const SHEEP: string = "minecraft:sheep"
const CHICKEN: string = "minecraft:chicken"
const HORSE: string = "minecraft:horse"
const DONKEY: string = "minecraft:donkey"
const MULE: string = "minecraft:mule"
const RABBIT: string = "minecraft:rabbit"
const COD: string = "minecraft:cod"
const SALMON: string = "minecraft:salmon"
const TROPICAL_FISH: string = "minecraft:tropical_fish"
const PUFFERFISH: string = "minecraft:pufferfish"
const SQUID: string = "minecraft:squid"
const GLOW_SQUID: string = "minecraft:glow_squid"
const BAT: string = "minecraft:bat"
const VILLAGER: string = "minecraft:villager"
const WANDERING_TRADER: string = "minecraft:wandering_trader"
const SNOW_GOLEM: string = "minecraft:snow_golem"
const STRIDER: string = "minecraft:strider"
const AXOLOTL: string = "minecraft:axolotl"
const FROG: string = "minecraft:frog"
const TADPOLE: string = "minecraft:tadpole"
const ALLAY: string = "minecraft:allay"
const SNIFFER: string = "minecraft:sniffer"
const ARMADILLO: string = "minecraft:armadillo"
const TURTLE: string = "minecraft:turtle"

// Neutral mobs
const WOLF: string = "minecraft:wolf"
const BEE: string = "minecraft:bee"
const POLAR_BEAR: string = "minecraft:polar_bear"
const DOLPHIN: string = "minecraft:dolphin"
const IRON_GOLEM: string = "minecraft:iron_golem"
const PIGLIN: string = "minecraft:piglin"
const ZOMBIFIED_PIGLIN: string = "minecraft:zombified_piglin"
const PANDA: string = "minecraft:panda"
const LLAMA: string = "minecraft:llama"
const TRADER_LLAMA: string = "minecraft:trader_llama"
const CAT: string = "minecraft:cat"
const OCELOT: string = "minecraft:ocelot"
const FOX: string = "minecraft:fox"
const GOAT: string = "minecraft:goat"
const CAMEL: string = "minecraft:camel"

// Bosses
const ENDER_DRAGON: string = "minecraft:ender_dragon"
const WITHER: string = "minecraft:wither"

// Special / misc
const ARMOR_STAND: string = "minecraft:armor_stand"
const ITEM_FRAME: string = "minecraft:item_frame"
const GLOW_ITEM_FRAME: string = "minecraft:glow_item_frame"
const PAINTING: string = "minecraft:painting"
const BOAT: string = "minecraft:boat"
const MINECART: string = "minecraft:minecart"
const TNT: string = "minecraft:tnt"
const FALLING_BLOCK: string = "minecraft:falling_block"
const ITEM: string = "minecraft:item"
const XP_ORB: string = "minecraft:experience_orb"
const FIREBALL: string = "minecraft:fireball"
const PLAYER: string = "minecraft:player"
